apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUzTVRVM01EZzNOakFlRncweE9URXdNakF4TVRJM05UWmFGdzB5T1RFd01UY3hNVEkzTlRaYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUzTVRVM01EZzNOakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk1ONUg4RWNCZlR6ZGVzMzRkZVRsRUpwUmp5SVJBUnBPV0NrdlpYQ0dGRlMKaE1qR0RaTmgvRC9zb3E3UVI3VUp1RHZqKzdybUdIV0kyVnRrNjRZTTdoNmpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUMxSkI0c3l2dTg0Cm5MVWVOaHlMZUIydDVCNlJkdWFldEJialUwNXQwRzNpQWlFQWxNRUJKK2RnbEExNGdCTGY4SEFvVEVZajh3WU4KQko2cWZkb1k3NXRmUXIwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://k3d-shipyard-server:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: fd174f0abc766794c5663c2932c0592b
    username: admin
